if ( isMultiplayer ) then {
	CONST_DIFFICULTY_MODIFIER = ["Difficulty",1] call bis_fnc_getParamValue;
	CONST_TIME_FACTOR = ["DayDuration",12] call bis_fnc_getParamValue;
	CONST_RSC_MULTIPLIER = ["ResourcesMultiplier",1] call bis_fnc_getParamValue;
	CONST_FATIGUE = ["Fatigue",1] call bis_fnc_getParamValue;
	CONST_REVIVE = ["Revive",3] call bis_fnc_getParamValue;
	CONST_INTRO = ["Introduction",1] call bis_fnc_getParamValue;
	CONST_DEPLOYMENT_CINEMATIC = ["DeploymentCinematic",1] call bis_fnc_getParamValue;
	CONST_UNITCAP = ["Unitcap",1] call bis_fnc_getParamValue;
	CONST_ADAPTIVE_OPFOR = ["AdaptToPlayercount",1] call bis_fnc_getParamValue;
	CONST_CIV = ["civilians",1] call bis_fnc_getParamValue;
	CONST_TEAMKILL_PENALTY = ["TeamkillPenalty",0] call bis_fnc_getParamValue;
	CONST_BUILD_FIRST_FOB = ["FirstFob",0] call bis_fnc_getParamValue;
	CONST_WIPE_SAVE1 = ["WipeSave1",0] call bis_fnc_getParamValue;
	CONST_WIPE_SAVE2 = ["WipeSave2",0] call bis_fnc_getParamValue;
	CONST_PASSIVE_INCOME = ["PassiveIncome",0] call bis_fnc_getParamValue;
	CONST_PLAYER_PERMISSION = ["Permissions",1] call bis_fnc_getParamValue;
	CONST_HALO = ["HaloJump",1] call bis_fnc_getParamValue;
	CONST_WHITELIST = ["Whitelist",0] call bis_fnc_getParamValue;
	CONST_CLEANUP = ["CleanupVehicles",2] call bis_fnc_getParamValue;
	CONST_CSAT_AGGRESSIVITY = ["Aggressivity",1] call bis_fnc_getParamValue;
	CONST_WEATHER = ["Weather",3] call bis_fnc_getParamValue;
	CONST_SHORT_NIGHTS = ["ShorterNights",0] call bis_fnc_getParamValue;
	CONST_AMMO_BOUNTIES = [ "AmmoBounties",0] call bis_fnc_getParamValue;
	CONST_CIV_PENALTIES = [ "CivPenalties",0] call bis_fnc_getParamValue;
	CONST_REMOTE_SENSORS = [ "DisableRemoteSensors",0] call bis_fnc_getParamValue;
	CONST_BLUFOR_DEF = [ "BluforDefenders",1] call bis_fnc_getParamValue;
	CONST_AUTODANGER = [ "Autodanger",0] call bis_fnc_getParamValue;
	CONST_MAX_FOBS = [ "MaximumFobs",26] call bis_fnc_getParamValue;
	CONST_MAX_SQUAD_SIZE = ["MaxSquadSize",100] call bis_fnc_getParamValue;
} else {
	CONST_DIFFICULTY_MODIFIER = 1;
	CONST_TIME_FACTOR = 12;
	CONST_RSC_MULTIPLIER = 1;
	CONST_FATIGUE = 1;
	CONST_REVIVE = 3;
	CONST_INTRO = 0;
	CONST_DEPLOYMENT_CINEMATIC = 0;
	CONST_ADAPTIVE_OPFOR = 1;
	CONST_UNITCAP = 1;
	CONST_CIV = 1;
	CONST_TEAMKILL_PENALTY = 0;
	CONST_BUILD_FIRST_FOB = 0;
	CONST_WIPE_SAVE1 = 0;
	CONST_WIPE_SAVE2 = 0;
	CONST_PASSIVE_INCOME = 0;
	CONST_PLAYER_PERMISSION = 1;
	CONST_HALO = 1;
	CONST_WHITELIST = 0;
	CONST_CLEANUP = 2;
	CONST_CSAT_AGGRESSIVITY = 1;
	CONST_WEATHER = 3;
	CONST_SHORT_NIGHTS = 0;
	CONST_AMMO_BOUNTIES = 1;
	CONST_CIV_PENALTIES = 1;
	CONST_REMOTE_SENSORS = 0;
	CONST_BLUFOR_DEF = 1;
	CONST_AUTODANGER = 0;
	CONST_MAX_FOBS = 26;
	CONST_MAX_SQUAD_SIZE = 100;
};

CONST_FATIGUE = (CONST_FATIGUE >= 0.1);
CONST_INTRO = (CONST_INTRO == 1);
CONST_DEPLOYMENT_CINEMATIC = (CONST_DEPLOYMENT_CINEMATIC == 1);
CONST_BUILD_FIRST_FOB = (CONST_BUILD_FIRST_FOB == 1);
CONST_TEAMKILL_PENALTY = (CONST_TEAMKILL_PENALTY == 1);
CONST_ADAPTIVE_OPFOR = (CONST_ADAPTIVE_OPFOR == 1);
CONST_PASSIVE_INCOME = (CONST_PASSIVE_INCOME == 1);
CONST_PLAYER_PERMISSION = (CONST_PLAYER_PERMISSION == 1);
CONST_WHITELIST = (CONST_WHITELIST == 1);
CONST_SHORT_NIGHTS = (CONST_SHORT_NIGHTS == 1);
CONST_AMMO_BOUNTIES = (CONST_AMMO_BOUNTIES == 1);
CONST_CIV_PENALTIES = (CONST_CIV_PENALTIES == 1);
CONST_BLUFOR_DEF = (CONST_BLUFOR_DEF == 1);
CONST_AUTODANGER = (CONST_AUTODANGER == 1);
